name: Playwright Tests on Custom Runner
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:
env:
    URL: ${{ secrets.URL }}
    API_URL: ${{ secrets.API_URL }}
    USER_NAME: ${{ secrets.USER_NAME }}
    EMAIL: ${{ secrets.EMAIL }}
    PASSWORD: ${{ secrets.PASSWORD }}
jobs:
    setup-and-smoke-test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup
            - name: Run Smoke tests
              run: npm run smoke
            - name: Upload Playwright Reports
              uses: ./.github/actions/playwright-report
    sanity-test:
        needs: setup-and-smoke-test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup
            - name: Run Sanity tests
              run: npm run sanity
            - name: Upload Playwright Reports
              uses: ./.github/actions/playwright-report
    api-test:
        needs: setup-and-smoke-test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup
            - name: Run API tests
              run: npm run api
            - name: Upload Playwright Reports
              uses: ./.github/actions/playwright-report
    regression-test:
        needs: setup-and-smoke-test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup
            - name: Run Regression tests
              run: npm run regression
            - name: Upload Playwright Reports
              uses: ./.github/actions/playwright-report
