name: Playwright Tests on Custom Runner Extended

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:

env:
    URL: ${{ secrets.URL }}
    API_URL: ${{ secrets.API_URL }}
    USER_NAME: ${{ secrets.USER_NAME }}
    EMAIL: ${{ secrets.EMAIL }}
    PASSWORD: ${{ secrets.PASSWORD }}

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    setup-and-smoke-test:
        name: Setup and Smoke Test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup

            - name: Run Smoke tests
              id: smoke
              run: npm run smoke

            - name: Upload Playwright Reports
              if: always()
              uses: ./.github/actions/playwright-report
              with:
                  test-step-outcome: ${{ steps.smoke.outcome }}
                  json-report: false

    sanity-test:
        name: Sanity Test
        needs: setup-and-smoke-test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup

            - name: Run Sanity tests
              id: sanity
              run: npm run sanity

            - name: Upload Playwright Reports
              if: always()
              uses: ./.github/actions/playwright-report
              with:
                  test-step-outcome: ${{ steps.sanity.outcome }}
                  json-report: false

    api-test:
        name: API Test
        needs: setup-and-smoke-test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup

            - name: Run API tests
              id: api
              run: npm run api

            - name: Upload Playwright Reports
              if: always()
              uses: ./.github/actions/playwright-report
              with:
                  test-step-outcome: ${{ steps.api.outcome }}
                  json-report: false

    regression-test:
        name: Regression Test
        needs: setup-and-smoke-test
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Playwright Setup on Runner
              uses: ./.github/actions/playwright-setup

            - name: Run Regression tests
              id: regression
              run: npm run regression

            - name: Upload Playwright Reports
              if: always()
              uses: ./.github/actions/playwright-report
              with:
                  test-step-outcome: ${{ steps.regression.outcome }}
                  json-report: false

    merge-report:
        name: Merge Report
        if: always()
        needs: [setup-and-smoke-test, sanity-test, api-test, regression-test]
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                  key: modules-${{ hashFiles('package-lock.json') }}

            - name: Cache Playwright
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/ms-playwright
                  key: playwright-${{ hashFiles('package-lock.json') }}

            - name: Download Smoke Test Report
              if: steps.smoke.outcome == 'failure'
              uses: actions/download-artifact@v4
              with:
                  name: smoke-test HTML report
                  path: merged-reports/smoke-test

            - name: Download API Test Report
              if: steps.api.outcome == 'failure'
              uses: actions/download-artifact@v4
              with:
                  name: api-test HTML report
                  path: merged-reports/api-test

            - name: Download Regression Test Report
              if: steps.regression.outcome == 'failure'
              uses: actions/download-artifact@v4
              with:
                  name: regression-test HTML report
                  path: merged-reports/regression-test

            - name: Download Sanity Test Report
              if: steps.sanity.outcome == 'failure'
              uses: actions/download-artifact@v4
              with:
                  name: sanity-test HTML report
                  path: merged-reports/sanity-test

            - name: Merge HTML Reports
              run: |
                  mkdir -p merged-reports/html
                  for dir in merged-reports/*; do
                      if [ -f "$dir/index.html" ]; then
                          cp -r "$dir/"* merged-reports/html/
                      fi
                  done

            - name: Upload Merged Reports as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Merged HTML Reports
                  path: merged-reports/html/
                  retention-days: 3

    build-report:
        name: Build Report
        if: always()
        needs: merge-report
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download Merged HTML Reports
              uses: actions/download-artifact@v4
              with:
                  name: Merged HTML Reports
                  path: ./_site

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./_site

    depoloy-report:
        name: Deploy Report
        if: always()
        needs: build-report
        environment:
            name: github-pages
            url: 'https://idavidov13.github.io/Playwright-Framework/'
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
